apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-manager

resources:
  - namespace.yaml
  - resource-quota.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - api-configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ui-configmap.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - ingress.yaml
