apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: task-manager
type: Opaque
stringData:
  POSTGRES_DB: taskmanager
  POSTGRES_USER: taskmanager
  POSTGRES_PASSWORD: taskmanager
