apiVersion: v1
kind: ResourceQuota
metadata:
  name: task-manager-quota
  namespace: task-manager
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    persistentvolumeclaims: "5"
    pods: "20"
